'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Locale
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Locale
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zumwani.Cloud_Player.Locale", GetType(Locale).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Public Shared ReadOnly Property Delete() As String
            Get
                Return ResourceManager.GetString("Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file could not be found..
        '''</summary>
        Public Shared ReadOnly Property FileNotFound() As String
            Get
                Return ResourceManager.GetString("FileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file was not of a proper playlist format..
        '''</summary>
        Public Shared ReadOnly Property FileWasNotOfProperPlatlistFormat() As String
            Get
                Return ResourceManager.GetString("FileWasNotOfProperPlatlistFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General.
        '''</summary>
        Public Shared ReadOnly Property General() As String
            Get
                Return ResourceManager.GetString("General", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading.
        '''</summary>
        Public Shared ReadOnly Property Loading() As String
            Get
                Return ResourceManager.GetString("Loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The media file could not be played, a codec pack might be required..
        '''</summary>
        Public Shared ReadOnly Property MainWindow_LocalMediaFailed() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalMediaFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The media stream could not be played..
        '''</summary>
        Public Shared ReadOnly Property MainWindow_OnlineMediaFailed() As String
            Get
                Return ResourceManager.GetString("MainWindow_OnlineMediaFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open in explorer.
        '''</summary>
        Public Shared ReadOnly Property OpenInExplorer() As String
            Get
                Return ResourceManager.GetString("OpenInExplorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured while parsing file:.
        '''</summary>
        Public Shared ReadOnly Property PlaylistLoader_ErrorMessage() As String
            Get
                Return ResourceManager.GetString("PlaylistLoader_ErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Playlist version is either out of date or was generated with a newer version of Cloud Player.
        '''Playlist version: {0}, Generator version: {1}.
        '''</summary>
        Public Shared ReadOnly Property PlaylistLoader_UpgradeMessage() As String
            Get
                Return ResourceManager.GetString("PlaylistLoader_UpgradeMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retry.
        '''</summary>
        Public Shared ReadOnly Property Retry() As String
            Get
                Return ResourceManager.GetString("Retry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skip.
        '''</summary>
        Public Shared ReadOnly Property Skip() As String
            Get
                Return ResourceManager.GetString("Skip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Public Shared ReadOnly Property Unknown() As String
            Get
                Return ResourceManager.GetString("Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upgrade.
        '''</summary>
        Public Shared ReadOnly Property Upgrade() As String
            Get
                Return ResourceManager.GetString("Upgrade", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
