'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Locale
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zumwani.CloudPlayer.Locale", GetType(Locale).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Open.
    '''</summary>
    Friend Shared ReadOnly Property ListItem_Open() As String
        Get
            Return ResourceManager.GetString("ListItem_Open", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Open at {0}.
    '''</summary>
    Friend Shared ReadOnly Property ListItem_OpenAt() As String
        Get
            Return ResourceManager.GetString("ListItem_OpenAt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Open in {0}.
    '''</summary>
    Friend Shared ReadOnly Property ListItem_OpenIn() As String
        Get
            Return ResourceManager.GetString("ListItem_OpenIn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 1 video - {0}.
    '''</summary>
    Friend Shared ReadOnly Property ListItem_Playlist() As String
        Get
            Return ResourceManager.GetString("ListItem_Playlist", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} videos - {1}.
    '''</summary>
    Friend Shared ReadOnly Property ListItem_Playlist_PluralVideo() As String
        Get
            Return ResourceManager.GetString("ListItem_Playlist_PluralVideo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Stop.
    '''</summary>
    Friend Shared ReadOnly Property ListItem_Stop() As String
        Get
            Return ResourceManager.GetString("ListItem_Stop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to by {0}.
    '''</summary>
    Friend Shared ReadOnly Property ListItem_Video() As String
        Get
            Return ResourceManager.GetString("ListItem_Video", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to by {0} - {1}.
    '''</summary>
    Friend Shared ReadOnly Property ListItem_Video_Time() As String
        Get
            Return ResourceManager.GetString("ListItem_Video_Time", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loading.
    '''</summary>
    Friend Shared ReadOnly Property Loading() As String
        Get
            Return ResourceManager.GetString("Loading", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add playlist.
    '''</summary>
    Friend Shared ReadOnly Property MainWindow_AddPlaylist() As String
        Get
            Return ResourceManager.GetString("MainWindow_AddPlaylist", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add videos.
    '''</summary>
    Friend Shared ReadOnly Property MainWindow_AddVideo() As String
        Get
            Return ResourceManager.GetString("MainWindow_AddVideo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The playlist &apos;{0}&apos; could not be loaded due to an error.
    '''Generator version: &apos;{1}&apos;, Playlist version: &apos;unknown&apos;
    '''
    '''{2}.
    '''</summary>
    Friend Shared ReadOnly Property SplashScreen_Error() As String
        Get
            Return ResourceManager.GetString("SplashScreen_Error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The playlist &apos;{0}&apos; could not be loaded. It was generated using a different generator version than the installed one. 
    '''Generator version: &apos;{1}&apos;, Playlist version: &apos;{2}&apos;.
    '''
    '''What do you wish to do?.
    '''</summary>
    Friend Shared ReadOnly Property SplashScreen_Upgrade() As String
        Get
            Return ResourceManager.GetString("SplashScreen_Upgrade", resourceCulture)
        End Get
    End Property
End Class
