'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Misc
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Res
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("YouTubeV2.Net.Res", GetType(Res).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vq=hd180.
        '''</summary>
        Public Shared ReadOnly Property _1080pString() As String
            Get
                Return ResourceManager.GetString("_1080pString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vq=small.
        '''</summary>
        Public Shared ReadOnly Property _240pString() As String
            Get
                Return ResourceManager.GetString("_240pString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vq=medium.
        '''</summary>
        Public Shared ReadOnly Property _360pString() As String
            Get
                Return ResourceManager.GetString("_360pString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vq=large.
        '''</summary>
        Public Shared ReadOnly Property _480pString() As String
            Get
                Return ResourceManager.GetString("_480pString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vq=hd720.
        '''</summary>
        Public Shared ReadOnly Property _720pString() As String
            Get
                Return ResourceManager.GetString("_720pString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to autoplay=1.
        '''</summary>
        Public Shared ReadOnly Property AutoplayString() As String
            Get
                Return ResourceManager.GetString("AutoplayString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://gdata.youtube.com/schemas/2007/categories.cat.
        '''</summary>
        Public Shared ReadOnly Property Categories() As String
            Get
                Return ResourceManager.GetString("Categories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to category=.
        '''</summary>
        Public Shared ReadOnly Property CategoryString() As String
            Get
                Return ResourceManager.GetString("CategoryString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://gdata.youtube.com/feeds/api/users/.
        '''</summary>
        Public Shared ReadOnly Property ChannelAPI() As String
            Get
                Return ResourceManager.GetString("ChannelAPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to controls=2.
        '''</summary>
        Public Shared ReadOnly Property ControlsDelayHideString() As String
            Get
                Return ResourceManager.GetString("ControlsDelayHideString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to controls=0.
        '''</summary>
        Public Shared ReadOnly Property ControlsForceHideString() As String
            Get
                Return ResourceManager.GetString("ControlsForceHideString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to disablekb=1.
        '''</summary>
        Public Shared ReadOnly Property DisableKeyboardString() As String
            Get
                Return ResourceManager.GetString("DisableKeyboardString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.youtube.com/embed/.
        '''</summary>
        Public Shared ReadOnly Property Embed() As String
            Get
                Return ResourceManager.GetString("Embed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to end=.
        '''</summary>
        Public Shared ReadOnly Property EndString() As String
            Get
                Return ResourceManager.GetString("EndString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cc_load_policy=1.
        '''</summary>
        Public Shared ReadOnly Property ForceCaptionsString() As String
            Get
                Return ResourceManager.GetString("ForceCaptionsString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to theme=light.
        '''</summary>
        Public Shared ReadOnly Property ForceWhitePlayerString() As String
            Get
                Return ResourceManager.GetString("ForceWhitePlayerString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to color=white.
        '''</summary>
        Public Shared ReadOnly Property ForceWhiteProgressbar() As String
            Get
                Return ResourceManager.GetString("ForceWhiteProgressbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iv_load_policy=3.
        '''</summary>
        Public Shared ReadOnly Property HideAnnotationsString() As String
            Get
                Return ResourceManager.GetString("HideAnnotationsString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to modestbranding=1.
        '''</summary>
        Public Shared ReadOnly Property HideBrandingString() As String
            Get
                Return ResourceManager.GetString("HideBrandingString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fs=0.
        '''</summary>
        Public Shared ReadOnly Property HideFullscreenString() As String
            Get
                Return ResourceManager.GetString("HideFullscreenString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rel=0.
        '''</summary>
        Public Shared ReadOnly Property HideRelatedVideosString() As String
            Get
                Return ResourceManager.GetString("HideRelatedVideosString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to showinfo=0.
        '''</summary>
        Public Shared ReadOnly Property HideTitlebarString() As String
            Get
                Return ResourceManager.GetString("HideTitlebarString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to loop=1&amp;playlist=.
        '''</summary>
        Public Shared ReadOnly Property LoopVideoString() As String
            Get
                Return ResourceManager.GetString("LoopVideoString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://gdata.youtube.com/feeds/api/playlists/.
        '''</summary>
        Public Shared ReadOnly Property PlaylistAPI() As String
            Get
                Return ResourceManager.GetString("PlaylistAPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://gdata.youtube.com/feeds/api/videos?q=.
        '''</summary>
        Public Shared ReadOnly Property SearchAPI() As String
            Get
                Return ResourceManager.GetString("SearchAPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to start=.
        '''</summary>
        Public Shared ReadOnly Property StartString() As String
            Get
                Return ResourceManager.GetString("StartString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to autohide=0.
        '''</summary>
        Public Shared ReadOnly Property UIForceShowString() As String
            Get
                Return ResourceManager.GetString("UIForceShowString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to autohide=2.
        '''</summary>
        Public Shared ReadOnly Property UIProgressbarHideString() As String
            Get
                Return ResourceManager.GetString("UIProgressbarHideString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://gdata.youtube.com/feeds/api/videos/.
        '''</summary>
        Public Shared ReadOnly Property VideoAPI() As String
            Get
                Return ResourceManager.GetString("VideoAPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.youtube.com/favicon.ico.
        '''</summary>
        Public Shared ReadOnly Property YouTubeIcon() As String
            Get
                Return ResourceManager.GetString("YouTubeIcon", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
